#ifndef HAT_CONFIG_REPORT_CHANNELS
#define HAT_CONFIG_REPORT_CHANNELS

#include <colour.h>

#define CHANNELS \
  ({ COLOUR_INTENSE_YELLOW, COLOUR_INTENSE_RED, COLOUR_INTENSE_CYAN })

#define INFORM_IDX  0
#define QC_IDX      1
#define BALANCE_IDX 2

#endif