#ifndef HAT_CONFIG_REPORT_CHANNELS
#define HAT_CONFIG_REPORT_CHANNELS

#include <colour.h>

#define CHANNELS \
  ({ COLOUR_INTENSE_YELLOW, COLOUR_INTENSE_RED, COLOUR_INTENSE_CYAN })

#define INFORM_CHANNEL  0
#define QC_CHANNEL      1
#define BALANCE_CHANNEL 2

#endif